package gui;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import util.AlgoritmoHuffman;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Administrador
 */
public class Apresentacao extends javax.swing.JFrame {

    /**
     * Creates new form Apresentacao
     */
    public Apresentacao() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Trabalho de Estrutura 2");
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rd_compactar = new javax.swing.JRadioButton();
        rd_descompactar = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        tf_arquivo_origem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_arquivo_destino = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(rd_compactar);
        rd_compactar.setSelected(true);
        rd_compactar.setText("Compactar");

        buttonGroup1.add(rd_descompactar);
        rd_descompactar.setText("Descompactar");

        jLabel1.setText("Arquivo Origem");

        tf_arquivo_origem.setEditable(false);
        tf_arquivo_origem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_arquivo_origemMouseClicked(evt);
            }
        });

        jLabel2.setText("Arquivo Destino");

        tf_arquivo_destino.setEditable(false);
        tf_arquivo_destino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_arquivo_destinoMouseClicked(evt);
            }
        });

        jButton1.setText("Processar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_arquivo_origem)
                    .addComponent(tf_arquivo_destino)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rd_compactar)
                            .addComponent(rd_descompactar)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 272, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rd_compactar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd_descompactar)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_arquivo_origem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_arquivo_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_arquivo_origemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_arquivo_origemMouseClicked
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser(tf_arquivo_origem.getText());
        jfc.setDialogTitle("Selecionar caminho");
        jfc.setApproveButtonText("Selecionar");

        if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            this.tf_arquivo_origem.setText(jfc.getSelectedFile().toString());
        }
    }//GEN-LAST:event_tf_arquivo_origemMouseClicked

    private void tf_arquivo_destinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_arquivo_destinoMouseClicked
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser(tf_arquivo_destino.getText());
        jfc.setDialogTitle("Selecionar caminho");
        jfc.setApproveButtonText("Selecionar");

        if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            this.tf_arquivo_destino.setText(jfc.getSelectedFile().toString());
        }
    }//GEN-LAST:event_tf_arquivo_destinoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (this.rd_compactar.isSelected()) {
            AlgoritmoHuffman.compactar(this.tf_arquivo_origem.getText(),
                    this.tf_arquivo_destino.getText());
            JOptionPane.showMessageDialog(this, "Compactado");
        } else {
            AlgoritmoHuffman.descompactar(this.tf_arquivo_origem.getText(),
                    this.tf_arquivo_destino.getText());
            JOptionPane.showMessageDialog(this, "Descompactado");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apresentacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rd_compactar;
    private javax.swing.JRadioButton rd_descompactar;
    private javax.swing.JTextField tf_arquivo_destino;
    private javax.swing.JTextField tf_arquivo_origem;
    // End of variables declaration//GEN-END:variables
}
